using LMS.Application.DTOs.CompOff;
using LMS.Application.Interfaces;
using LMS.Domain.Common;
using LMS.Domain.Entities;
using LMS.Domain.Enums;
using LMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace LMS.Infrastructure.Services;

/// <summary>
/// Handles the comp-off request lifecycle: Submit, Approve, Reject.
/// Business rules (COMPOFF-API-001):
///   - worked_hours >= 4 required (422 otherwise) — UT-43
///   - worked_date must NOT be a working day (422 if it is)
///   - UNIQUE(employee_id, worked_date) → 409
///   - Audit on every state change (CONSTITUTION Art VII)
/// Credits are generated by ICompOffCreditService on Approve.
/// </summary>
public class CompOffRequestService : ICompOffRequestService
{
    private readonly LmsDbContext          _db;
    private readonly IHolidayService       _holidayService;
    private readonly IAuditService         _auditService;
    private readonly ICompOffCreditService _creditService;

    public CompOffRequestService(
        LmsDbContext          db,
        IHolidayService       holidayService,
        IAuditService         auditService,
        ICompOffCreditService creditService)
    {
        _db             = db;
        _holidayService = holidayService;
        _auditService   = auditService;
        _creditService  = creditService;
    }

    /// <inheritdoc/>
    public async Task<Result<CompOffRequestDto>> SubmitAsync(
        Guid employeeId, CreateCompOffRequestDto dto)
    {
        // UT-43: hours < 4 → 422
        if (dto.WorkedHours < 4m)
            return Result<CompOffRequestDto>.Failure(
                "Worked hours must be at least 4 to qualify for comp-off.", 422);

        // worked_date must NOT be a regular working day → 422
        var workingDayResult = await _holidayService.IsWorkingDayAsync(dto.WorkedDate);
        if (!workingDayResult.IsSuccess)
            return Result<CompOffRequestDto>.Failure(workingDayResult.Error!, 400);

        if (workingDayResult.Value)
            return Result<CompOffRequestDto>.Failure(
                "Comp-off can only be claimed for non-working days (weekends or public holidays).", 422);

        // UNIQUE(employee_id, worked_date) → 409
        var duplicate = await _db.CompOffRequests.AnyAsync(
            r => r.EmployeeId == employeeId && r.WorkedDate == dto.WorkedDate);
        if (duplicate)
            return Result<CompOffRequestDto>.Failure(
                "A comp-off request for this date already exists.", 409);

        var now = DateTime.UtcNow;
        var request = new CompOffRequest
        {
            Id          = Guid.NewGuid(),
            EmployeeId  = employeeId,
            WorkedDate  = dto.WorkedDate,
            WorkedHours = dto.WorkedHours,
            Status      = CompOffStatus.Pending,
            CreatedAt   = now,
            UpdatedAt   = now,
        };

        _db.CompOffRequests.Add(request);
        await _db.SaveChangesAsync();

        await _auditService.LogAsync(
            action:     "CompOffRequest.Submit",
            entityType: "CompOffRequest",
            entityId:   request.Id,
            actorId:    employeeId,
            oldValue:   null,
            newValue:   new { request.WorkedDate, request.WorkedHours, Status = request.Status.ToString() });

        return Result<CompOffRequestDto>.Success(ToDto(request));
    }

    /// <inheritdoc/>
    public async Task<Result<CompOffRequestDto>> ApproveAsync(
        Guid requestId, Guid approverId)
    {
        var request = await _db.CompOffRequests.FindAsync(requestId);
        if (request is null)
            return Result<CompOffRequestDto>.Failure("Comp-off request not found.", 404);

        if (request.Status != CompOffStatus.Pending)
            return Result<CompOffRequestDto>.Failure(
                "Only pending requests can be approved.", 400);

        var oldStatus     = request.Status;
        request.Status    = CompOffStatus.Approved;
        request.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        // Generate credit and update leave balance
        var creditResult = await _creditService.CreditBalanceAsync(requestId);
        if (!creditResult.IsSuccess)
            return Result<CompOffRequestDto>.Failure(
                creditResult.Error!, creditResult.StatusCode);

        await _auditService.LogAsync(
            action:     "CompOffRequest.Approve",
            entityType: "CompOffRequest",
            entityId:   request.Id,
            actorId:    approverId,
            oldValue:   new { Status = oldStatus.ToString() },
            newValue:   new { Status = request.Status.ToString() });

        return Result<CompOffRequestDto>.Success(ToDto(request));
    }

    /// <inheritdoc/>
    public async Task<Result<CompOffRequestDto>> RejectAsync(
        Guid requestId, Guid approverId)
    {
        var request = await _db.CompOffRequests.FindAsync(requestId);
        if (request is null)
            return Result<CompOffRequestDto>.Failure("Comp-off request not found.", 404);

        if (request.Status != CompOffStatus.Pending)
            return Result<CompOffRequestDto>.Failure(
                "Only pending requests can be rejected.", 400);

        var oldStatus     = request.Status;
        request.Status    = CompOffStatus.Rejected;
        request.UpdatedAt = DateTime.UtcNow;
        await _db.SaveChangesAsync();

        await _auditService.LogAsync(
            action:     "CompOffRequest.Reject",
            entityType: "CompOffRequest",
            entityId:   request.Id,
            actorId:    approverId,
            oldValue:   new { Status = oldStatus.ToString() },
            newValue:   new { Status = request.Status.ToString() });

        return Result<CompOffRequestDto>.Success(ToDto(request));
    }

    /// <inheritdoc/>
    public async Task<Result<List<CompOffRequestDto>>> GetMyRequestsAsync(Guid employeeId)
    {
        var requests = await _db.CompOffRequests
            .AsNoTracking()
            .Where(r => r.EmployeeId == employeeId)
            .OrderByDescending(r => r.CreatedAt)
            .ToListAsync();

        return Result<List<CompOffRequestDto>>.Success(
            requests.Select(ToDto).ToList());
    }

    // ── helpers ──────────────────────────────────────────────────────────────

    private static CompOffRequestDto ToDto(CompOffRequest r) => new()
    {
        Id          = r.Id,
        EmployeeId  = r.EmployeeId,
        WorkedDate  = r.WorkedDate,
        WorkedHours = r.WorkedHours,
        Status      = r.Status.ToString(),
        CreatedAt   = r.CreatedAt,
        UpdatedAt   = r.UpdatedAt,
    };
}
