using LMS.Domain.Enums;

namespace LMS.Domain.Entities;

/// <summary>
/// A single step in the multi-level approval chain for a leave request.
/// Steps are ordered by <see cref="StepNumber"/> (1 = L1, 2 = L2).
/// Cascade-deleted when the parent LeaveRequest is deleted.
/// </summary>
public class ApprovalStep
{
    /// <summary>Primary key — UUID generated by PostgreSQL gen_random_uuid().</summary>
    public Guid Id { get; set; }

    /// <summary>FK to the parent leave request. CASCADE DELETE is enforced at the DB level.</summary>
    public Guid LeaveRequestId { get; set; }

    /// <summary>Approval level: 1 = L1 (direct manager), 2 = L2 (HR Admin / skip-level).</summary>
    public short StepNumber { get; set; }

    /// <summary>FK to the user who is the designated approver for this step.</summary>
    public Guid ApproverId { get; set; }

    /// <summary>Current status of this approval step.</summary>
    public ApprovalStepStatus Status { get; set; } = ApprovalStepStatus.Pending;

    /// <summary>UTC timestamp when the approver took action. Null until actioned.</summary>
    public DateTime? ActedAt { get; set; }

    /// <summary>Optional comment left by the approver when approving or rejecting.</summary>
    public string? Comment { get; set; }

    /// <summary>UTC timestamp when this step record was created.</summary>
    public DateTime CreatedAt { get; set; }

    // Navigation properties

    /// <summary>The parent leave request.</summary>
    public LeaveRequest LeaveRequest { get; set; } = null!;

    /// <summary>The user designated as approver for this step.</summary>
    public User Approver { get; set; } = null!;
}
