using LMS.Domain.Enums;

namespace LMS.Domain.Entities;

/// <summary>
/// Records a worked day (weekend or public holiday) that qualifies an employee
/// for compensatory-off credit.
/// Credit conversion (4 h = 0.5 day, 8 h = 1 day) is computed in CompOffCreditService,
/// not stored here.
/// </summary>
public class CompOffRequest
{
    /// <summary>Surrogate primary key (UUID, generated by DB).</summary>
    public Guid Id { get; set; }

    /// <summary>FK to the employee who worked the extra day.</summary>
    public Guid EmployeeId { get; set; }

    /// <summary>Calendar date on which extra work was performed.</summary>
    public DateOnly WorkedDate { get; set; }

    /// <summary>
    /// Hours worked on that date (e.g. 4.0 or 8.0).
    /// Stored as numeric(4,1).
    /// </summary>
    public decimal WorkedHours { get; set; }

    /// <summary>Approval lifecycle status (default: Pending).</summary>
    public CompOffStatus Status { get; set; } = CompOffStatus.Pending;

    /// <summary>UTC timestamp when this record was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp of the last status update.</summary>
    public DateTime UpdatedAt { get; set; }

    // ── Navigation ──────────────────────────────────────────────────────────

    /// <summary>The employee who submitted the request.</summary>
    public User Employee { get; set; } = null!;

    /// <summary>
    /// Credits generated from this request (populated on approval).
    /// </summary>
    public ICollection<CompOffCredit> Credits { get; set; } = new List<CompOffCredit>();
}
