namespace LMS.Domain.Entities;

/// <summary>
/// A comp-off balance credit granted when a <see cref="CompOffRequest"/> is approved.
/// Expiry is set to <c>worked_date + 180 days</c> by CompOffCreditService — not a DB trigger.
/// Credit amounts: 4 h worked → 0.5 day credit, 8 h worked → 1.0 day credit.
/// </summary>
public class CompOffCredit
{
    /// <summary>Surrogate primary key (UUID, generated by DB).</summary>
    public Guid Id { get; set; }

    /// <summary>FK to the employee receiving the credit.</summary>
    public Guid EmployeeId { get; set; }

    /// <summary>FK to the approved comp-off request that generated this credit.</summary>
    public Guid CompOffRequestId { get; set; }

    /// <summary>
    /// Number of credit days granted (0.5 or 1.0).
    /// Stored as numeric(3,1).
    /// </summary>
    public decimal CreditDays { get; set; }

    /// <summary>
    /// Date after which this credit can no longer be used
    /// (= worked_date + 180 days, set by CompOffCreditService).
    /// </summary>
    public DateOnly ExpiresAt { get; set; }

    /// <summary>
    /// Credit days already consumed (0 until applied to a leave request).
    /// Stored as numeric(3,1), default 0.
    /// </summary>
    public decimal UsedDays { get; set; } = 0;

    /// <summary>UTC timestamp when this credit record was created.</summary>
    public DateTime CreatedAt { get; set; }

    // ── Navigation ──────────────────────────────────────────────────────────

    /// <summary>The employee who received the credit.</summary>
    public User Employee { get; set; } = null!;

    /// <summary>The originating comp-off request.</summary>
    public CompOffRequest CompOffRequest { get; set; } = null!;
}
