using LMS.Domain.Enums;

namespace LMS.Domain.Entities;

/// <summary>
/// Represents an employee leave request in the LMS system.
/// A request progresses through Draft → Pending → Approved/Rejected/Cancelled/Revoked.
/// </summary>
public class LeaveRequest
{
    /// <summary>Primary key — UUID generated by PostgreSQL gen_random_uuid().</summary>
    public Guid Id { get; set; }

    /// <summary>FK to the employee (user) who submitted the request.</summary>
    public Guid EmployeeId { get; set; }

    /// <summary>FK to the leave type (Annual, Sick, Unpaid, etc.).</summary>
    public Guid LeaveTypeId { get; set; }

    /// <summary>First calendar day of the requested leave period (inclusive).</summary>
    public DateOnly StartDate { get; set; }

    /// <summary>Last calendar day of the requested leave period (inclusive).</summary>
    public DateOnly EndDate { get; set; }

    /// <summary>
    /// Working days consumed by this request, calculated by the SandwichRuleEngine.
    /// Stored with one decimal place to represent half-day leaves (0.5).
    /// </summary>
    public decimal ComputedDays { get; set; } = 0m;

    /// <summary>Current lifecycle status of the request.</summary>
    public LeaveRequestStatus Status { get; set; } = LeaveRequestStatus.Draft;

    /// <summary>
    /// True when the request covers a period that has already passed.
    /// Retroactive requests bypass the future-date pre-check.
    /// No-manager rule still applies unconditionally (UT-53).
    /// </summary>
    public bool IsRetroactive { get; set; } = false;

    /// <summary>Employee-provided reason for the leave.</summary>
    public string Reason { get; set; } = string.Empty;

    /// <summary>Optional URL to a supporting document (e.g. medical certificate).</summary>
    public string? DocumentUrl { get; set; }

    /// <summary>UTC timestamp when the record was created.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>UTC timestamp of the last modification.</summary>
    public DateTime UpdatedAt { get; set; }

    // Navigation properties

    /// <summary>The employee who made the request.</summary>
    public User Employee { get; set; } = null!;

    /// <summary>The leave type chosen for this request.</summary>
    public LeaveType LeaveType { get; set; } = null!;

    /// <summary>Ordered list of approval steps generated when the request is submitted.</summary>
    public ICollection<ApprovalStep> ApprovalSteps { get; set; } = new List<ApprovalStep>();
}
