using LMS.Domain.Enums;

namespace LMS.Domain.Entities;

/// <summary>
/// An in-app notification delivered to a specific user.
/// Notifications are immutable once created; only <see cref="IsRead"/> changes.
/// </summary>
public class Notification
{
    /// <summary>Surrogate primary key (UUID, generated by DB).</summary>
    public Guid Id { get; set; }

    /// <summary>FK to the user who receives this notification.</summary>
    public Guid UserId { get; set; }

    /// <summary>Event type that triggered the notification.</summary>
    public NotificationType Type { get; set; }

    /// <summary>Short notification heading (max 200 chars).</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Full notification body text.</summary>
    public string Body { get; set; } = string.Empty;

    /// <summary>Whether the user has read this notification (default false).</summary>
    public bool IsRead { get; set; } = false;

    /// <summary>
    /// Optional: the resource type this notification refers to
    /// (e.g. "LeaveRequest", "CompOffRequest"). Max 50 chars.
    /// </summary>
    public string? ResourceType { get; set; }

    /// <summary>
    /// Optional: the UUID of the referenced resource, enabling deep-link navigation.
    /// </summary>
    public Guid? ResourceId { get; set; }

    /// <summary>UTC timestamp when this notification was created.</summary>
    public DateTime CreatedAt { get; set; }

    // ── Navigation ──────────────────────────────────────────────────────────

    /// <summary>The recipient user.</summary>
    public User User { get; set; } = null!;
}
