using LMS.Application.DTOs.CompOff;
using LMS.Domain.Common;

namespace LMS.Application.Interfaces;

/// <summary>
/// Service contract for comp-off request lifecycle management.
/// Submit → Approve/Reject. Credits are generated by ICompOffCreditService on approval.
/// Business rules (COMPOFF-API-001):
///   - worked_hours must be >= 4 (422 otherwise)
///   - worked_date must NOT be a regular working day (422 if it is)
///   - UNIQUE(employee_id, worked_date) — duplicate → 409
/// </summary>
public interface ICompOffRequestService
{
    /// <summary>
    /// Submits a new comp-off request for <paramref name="employeeId"/>.
    /// Returns 422 if hours &lt; 4 or worked_date is a working day.
    /// Returns 409 on duplicate (employee_id, worked_date).
    /// </summary>
    Task<Result<CompOffRequestDto>> SubmitAsync(
        Guid employeeId, CreateCompOffRequestDto dto);

    /// <summary>
    /// Approves a pending comp-off request.
    /// Delegates credit generation to <see cref="ICompOffCreditService"/>.
    /// Audits the transition.
    /// </summary>
    Task<Result<CompOffRequestDto>> ApproveAsync(Guid requestId, Guid approverId);

    /// <summary>
    /// Rejects a pending comp-off request. No credit is generated.
    /// Audits the transition.
    /// </summary>
    Task<Result<CompOffRequestDto>> RejectAsync(Guid requestId, Guid approverId);

    /// <summary>
    /// Returns all comp-off requests for the given employee, newest first.
    /// </summary>
    Task<Result<List<CompOffRequestDto>>> GetMyRequestsAsync(Guid employeeId);
}
